# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d2cc3b54ad49cf6edd5a59cc2eff2f5dcb0c76e90b88e51101305d85e2736b7770136f73186ae0fb8cf64dcf19f225fc47b159a15151791707fbacca6eb9be8

test:
  secret_key_base: 35522d36e300abeee4bbc2ffdad521203d4cf70b7457328e55a4d6f1d286ecc9ba99d1225deb16405dbf9960262a7cea274eb020034b344a42f8da854a91cac4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
